/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DynamicFromRouteImport } from './routes/dynamic-from'
import { Route as DynamicFromManifestRouteImport } from './routes/dynamic-from.manifest'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'

const DynamicFromRoute = DynamicFromRouteImport.update({
  id: '/dynamic-from',
  path: '/dynamic-from',
  getParentRoute: () => rootRouteImport,
} as any)
const DynamicFromManifestRoute = DynamicFromManifestRouteImport.update({
  id: '/manifest',
  path: '/manifest',
  getParentRoute: () => DynamicFromRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/dynamic-from': typeof DynamicFromRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dynamic-from/manifest': typeof DynamicFromManifestRoute
}
export interface FileRoutesByTo {
  '/dynamic-from': typeof DynamicFromRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dynamic-from/manifest': typeof DynamicFromManifestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dynamic-from': typeof DynamicFromRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dynamic-from/manifest': typeof DynamicFromManifestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/dynamic-from' | '/demo/tanstack-query' | '/dynamic-from/manifest'
  fileRoutesByTo: FileRoutesByTo
  to: '/dynamic-from' | '/demo/tanstack-query' | '/dynamic-from/manifest'
  id:
    | '__root__'
    | '/dynamic-from'
    | '/demo/tanstack-query'
    | '/dynamic-from/manifest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DynamicFromRoute: typeof DynamicFromRouteWithChildren
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dynamic-from': {
      id: '/dynamic-from'
      path: '/dynamic-from'
      fullPath: '/dynamic-from'
      preLoaderRoute: typeof DynamicFromRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dynamic-from/manifest': {
      id: '/dynamic-from/manifest'
      path: '/manifest'
      fullPath: '/dynamic-from/manifest'
      preLoaderRoute: typeof DynamicFromManifestRouteImport
      parentRoute: typeof DynamicFromRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DynamicFromRouteChildren {
  DynamicFromManifestRoute: typeof DynamicFromManifestRoute
}

const DynamicFromRouteChildren: DynamicFromRouteChildren = {
  DynamicFromManifestRoute: DynamicFromManifestRoute,
}

const DynamicFromRouteWithChildren = DynamicFromRoute._addFileChildren(
  DynamicFromRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DynamicFromRoute: DynamicFromRouteWithChildren,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
