/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DynamicFromIndexRouteImport } from './routes/dynamic-from/index'
import { Route as DynamicFromManifestRouteImport } from './routes/dynamic-from/manifest'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'

const DynamicFromIndexRoute = DynamicFromIndexRouteImport.update({
  id: '/dynamic-from/',
  path: '/dynamic-from/',
  getParentRoute: () => rootRouteImport,
} as any)
const DynamicFromManifestRoute = DynamicFromManifestRouteImport.update({
  id: '/dynamic-from/manifest',
  path: '/dynamic-from/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dynamic-from/manifest': typeof DynamicFromManifestRoute
  '/dynamic-from': typeof DynamicFromIndexRoute
}
export interface FileRoutesByTo {
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dynamic-from/manifest': typeof DynamicFromManifestRoute
  '/dynamic-from': typeof DynamicFromIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dynamic-from/manifest': typeof DynamicFromManifestRoute
  '/dynamic-from/': typeof DynamicFromIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/demo/tanstack-query' | '/dynamic-from/manifest' | '/dynamic-from'
  fileRoutesByTo: FileRoutesByTo
  to: '/demo/tanstack-query' | '/dynamic-from/manifest' | '/dynamic-from'
  id:
    | '__root__'
    | '/demo/tanstack-query'
    | '/dynamic-from/manifest'
    | '/dynamic-from/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DynamicFromManifestRoute: typeof DynamicFromManifestRoute
  DynamicFromIndexRoute: typeof DynamicFromIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dynamic-from/': {
      id: '/dynamic-from/'
      path: '/dynamic-from'
      fullPath: '/dynamic-from'
      preLoaderRoute: typeof DynamicFromIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dynamic-from/manifest': {
      id: '/dynamic-from/manifest'
      path: '/dynamic-from/manifest'
      fullPath: '/dynamic-from/manifest'
      preLoaderRoute: typeof DynamicFromManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DynamicFromManifestRoute: DynamicFromManifestRoute,
  DynamicFromIndexRoute: DynamicFromIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
